rate: 0.5 # control loop frequency [Hz]
parent_frame: world 
child_frame: vehicle 
max_iterations: 500 # maximum interations per control loop
gamma: 40 # RRT*
dist_threshold: 5 
angle_threshold: 0.3490658503988659 
step_size: 10.0 
goal_bias: 0.3 # proability that the goal is returned by sampler
tree_pub_topic: planner_tree # expose params for visualization.py
tree_sub_topic: rrts_tree
tree_line_width: 0.05