rate2: 10 # control loop frequency [Hz]
parent_frame: world # parent reference frame (world)
child_frame: vehicle # child reference frame (vehicle)
min_stop_distance: 0.4 # minimum distance from car to stopping point for car to stop (in meters)
stopping_time:  3.0 # duration for car at stop point (seconds)



