obstacle_range: 2.5
raytrace_range: 6.0

footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.0


publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.25

resolution: 0.05

obstacle_layer:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: false, marking: true, topic: scan, inf_is_valid: true}

static:
  map_topic: /map
  subscribe_to_updates: true

