global_costmap:
  global_frame: /odom
  robot_base_frame: /base_footprint
  static_map: false
  rolling_window: true
  width: 50
  height: 50


  plugins:
  - {name: obstacle_layer,         type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
