global_frame: map
robot_base_frame: ego_vehicle
update_frequency: 5
publish_frequency: 5
min_particles: 100
max_particles: 5000
kid_err: 0.01
kid_z: 0.99
update_min_d: 0.2
update_min_a: 0.523598776
resample_interval: 2
transform_tolerance: 0.1
recovery_alpha_fast: 0.0
initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0
initial_cov_xx: 0.25
initial_cov_yy: 0.25
initial_cov_aa: 0.068538919
gui_publish_rate: -1.0
save_pose_rate: 0.5
use_map_topic: false
first_map_only: false

laser_min_range: -1.0
laser_max_range: -1.0
laser_max_beams: 30
laser_z_hit: 0.95
laser_z_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_model_type: "likelihood_field"

odom_model_type: "diff"
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.2
odom_alpha5: 0.2
odom_frame_id: "odom"
base_frame_id: "base_link"
global_frame_id: "map"
tf_broadcast: true

plugins: 
  # - {name: static_map,       type: "costmap_2d::StaticLayer"}
  # - {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}
  # - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: ego_vehicle/lidar/lidar1, data_type: PointCloud2, topic: /carla/ego_vehicle/lidar/lidar1/point_cloud, marking: true, clearing: true}

# inflation_layer:
#   inflation_radius: 0.25