global_frame: map
robot_base_frame: ego_vehicle
update_frequency: 5
publish_frequency: 5
static_map: false 
rolling_window: true 
width: 20
height: 20
resolution: 1 
# footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]

plugins: 
  # - {name: static_map,       type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,        type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: ego_vehicle/lidar/lidar1, data_type: PointCloud2, topic: /carla/ego_vehicle/lidar/lidar1/point_cloud, marking: true, clearing: true}

inflation_layer:
  inflation_radius: 0.25
  
