rate: 1.0 # control loop frequency [Hz]
parent_frame: map # Parent Reference frame (world) TODO: set correct value
child_frame: ego_vehicle # Child Reference frame (vehicle) TODO: set correct value
lookahead: 4 # distance to goal point [m]
wheelbase: 0.3 # distance between vehicle's front and rear axles [m]
speed: 1 # vehicle's forward speed [m/s]
