rate: 1.0 # control loop frequency [Hz]
parent_frame: map # Parent Reference frame (world)
child_frame: ego_vehicle_filtered # Child Reference frame (vehicle)
wheelbase: 1 # distance between vehicle's front and reat axles [m]
lookahead_min: 3 # the minimum lookahead [m], additionallly the initial value of the lookahead
lookahead_max: 12 # the maximum lookahead [m]
lower_velocity_threshold: 1.34 # the lower threshold of the velocity that cooresponds to lookahead_min
upper_velocity_threshold: 5.36 # the above, but for max/upper
lookahead_gain: 2.24 # this is the scalar to multiply with v_cmd if in between the extremes
draw_speed_and_lookahead: True # True if the speed "X" and the lookahead circle should be drawn
